import 'server-only';
import { randomUUID } from 'node:crypto';
import { prisma } from '@schooz/database';
import { PERMISSIONS, requireSchoolPermission, type SchoolContext } from '../authorization';
import { AuthorizationError, ConflictError, NotFoundError } from '../errors';
import { auditService } from '../audit';
import { createAuthorizedDownloadUrl, deletePrivateObjectAtKey, uploadPrivateObjectAtKey, validateUploadMetadata, type UploadMetadata } from '../storage';
import { examDocumentInputSchema, type ExamDocumentType } from './schemas';
type DocDb = Pick<typeof prisma, 'examDocument' | 'exam' | 'academicClass' | 'subject' | 'classSubject'>;
const read = (c: SchoolContext) => requireSchoolPermission(c, PERMISSIONS.EXAMS_READ ?? PERMISSIONS.EXAMS_RESULTS_READ);
const manage = (c: SchoolContext) => requireSchoolPermission(c, PERMISSIONS.EXAMS_MANAGE ?? PERMISSIONS.EXAMS_RESULTS_MANAGE);
const missing = (m: string): never => { throw new NotFoundError(m); };
function extension(name: string) { return name.toLowerCase().split('.').pop() ?? ''; }
function assertExtension(name: string, mime: string) { const ext = extension(name); const allowed: Record<string, string[]> = { pdf:['pdf'], 'image/jpeg':['jpg','jpeg'], 'image/png':['png'], 'image/webp':['webp'], 'text/plain':['txt'], 'application/msword':['doc'], 'application/vnd.openxmlformats-officedocument.wordprocessingml.document':['docx'], 'application/vnd.ms-excel':['xls'], 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':['xlsx'], 'application/vnd.ms-powerpoint':['ppt'], 'application/vnd.openxmlformats-officedocument.presentationml.presentation':['pptx'] }; if (!allowed[mime]?.includes(ext)) throw new ConflictError('File extension does not match MIME type.'); }
async function assertSignature(file: Blob | ArrayBuffer | Uint8Array, mime: string) { if (mime === 'text/plain') return; const bytes = file instanceof Uint8Array ? file : file instanceof ArrayBuffer ? new Uint8Array(file) : new Uint8Array(await file.arrayBuffer()); const starts = (values: number[]) => values.every((v, i) => bytes[i] === v); const valid = mime === 'application/pdf' ? starts([37,80,68,70]) : mime === 'image/png' ? starts([137,80,78,71,13,10,26,10]) : mime === 'image/jpeg' ? starts([255,216,255]) : mime === 'image/webp' ? starts([82,73,70,70]) && bytes[8] === 87 && bytes[9] === 69 && bytes[10] === 66 && bytes[11] === 80 : starts([80,75,3,4]) || (mime === 'application/msword' && starts([208,207,17,224])); if (!valid) throw new ConflictError('File signature does not match MIME type.'); }
async function validateContext(context: SchoolContext, input: { examId: string; classId?: string; subjectId?: string }, db: DocDb) { const exam = await db.exam.findFirst({ where: { id: input.examId, schoolId: context.schoolId } }); if (!exam) return missing('Exam not found.'); if ((input.classId && !input.subjectId) || (!input.classId && input.subjectId)) throw new ConflictError('Class and subject must be supplied together.'); if (!input.classId) return exam; const [cls, subject, mapping] = await Promise.all([db.academicClass.findFirst({ where: { id: input.classId, schoolId: context.schoolId } }), db.subject.findFirst({ where: { id: input.subjectId!, schoolId: context.schoolId } }), db.classSubject.findFirst({ where: { schoolId: context.schoolId, academicYearId: exam.academicYearId, classId: input.classId, subjectId: input.subjectId! } })]); if (!cls || !subject || !mapping) missing('Document class and subject must belong to this exam school and academic year.'); return exam; }
function sensitive(type: ExamDocumentType) { return type === 'QUESTION_PAPER' || type === 'ANSWER_KEY'; }
export async function uploadExamDocument(context: SchoolContext, input: unknown, file: Blob | ArrayBuffer | Uint8Array, metadata: UploadMetadata, db: DocDb = prisma) { manage(context); const data = examDocumentInputSchema.parse(input); await validateContext(context, data, db); const valid = validateUploadMetadata(metadata); assertExtension(valid.originalName, valid.contentType); await assertSignature(file, valid.contentType); const key = `schools/${context.schoolId}/exams/${data.examId}/${randomUUID()}.${extension(valid.originalName)}`; const uploaded = await uploadPrivateObjectAtKey({ storageKey: key, allowedPrefix: `schools/${context.schoolId}/exams/${data.examId}`, file, metadata: valid }); try { const document = await db.examDocument.create({ data: { ...data, schoolId: context.schoolId, storageKey: uploaded.storageKey, originalFileName: valid.originalName, mimeType: valid.contentType, sizeBytes: valid.sizeBytes, uploadedByUserId: context.userId } }); await auditService.appendForSchool(context, { action:'EXAM_DOCUMENT_UPLOAD', entityType:'ExamDocument', entityId:document.id, actorType:'USER', metadata:{ examId:data.examId, type:data.type, sizeBytes:valid.sizeBytes } }); return document; } catch (error) { throw error; } }
export async function listExamDocuments(context: SchoolContext, examId: string, db: DocDb = prisma) { read(context); await validateContext(context, { examId }, db); return db.examDocument.findMany({ where: { schoolId: context.schoolId, examId }, select: { id:true, examId:true, classId:true, subjectId:true, type:true, originalFileName:true, mimeType:true, sizeBytes:true, uploadedByUserId:true, createdAt:true }, orderBy:{ createdAt:'desc' }, take:500 }); }
export async function getExamDocumentDownloadUrl(context: SchoolContext, documentId: string, storage?: Parameters<typeof createAuthorizedDownloadUrl>[0]['storage'], db: DocDb = prisma) { const document = await db.examDocument.findFirst({ where: { id:documentId, schoolId:context.schoolId }, select:{ id:true, examId:true, type:true, storageKey:true } }); if (!document) return missing('Exam document not found.'); if (sensitive(document.type as ExamDocumentType)) manage(context); else read(context); if (!document.storageKey.startsWith(`schools/${context.schoolId}/exams/${document.examId}/`)) throw new AuthorizationError(); return createAuthorizedDownloadUrl({ context, schoolId:context.schoolId, storageKey:document.storageKey, storage }); }
export async function deleteExamDocument(context: SchoolContext, documentId: string, db: DocDb = prisma) { manage(context); const document = await db.examDocument.findFirst({ where:{ id:documentId, schoolId:context.schoolId } }); if (!document) return missing('Exam document not found.'); await deletePrivateObjectAtKey({ storageKey:document.storageKey, allowedPrefix:`schools/${context.schoolId}/exams/${document.examId}` }); await db.examDocument.delete({ where:{ id:document.id } }); await auditService.appendForSchool(context, { action:'EXAM_DOCUMENT_DELETE', entityType:'ExamDocument', entityId:document.id, actorType:'USER', metadata:{ examId:document.examId, type:document.type } }); return { id:document.id }; }
