'use server';
import { redirect } from 'next/navigation';
import { contextForSchoolSlug } from '../settings/service';
import { archiveStudent, createGuardian, createStudentWithInitialEnrollment, linkGuardian, createEnrollment, setEnrollmentStatus, updateStudent } from './service';
const v = (fd: FormData, key: string) => { const x = fd.get(key); return typeof x === 'string' ? x : ''; };
const fail = (slug: string): never => redirect(`/s/${slug}/students?error=action-failed` as never);
export async function createStudentAction(fd: FormData) { const slug = v(fd, 'schoolSlug'); try { const c = await contextForSchoolSlug(slug); await createStudentWithInitialEnrollment(c, { admissionNumber: v(fd,'admissionNumber'), firstName: v(fd,'firstName'), lastName: v(fd,'lastName'), dateOfBirth: v(fd,'dateOfBirth'), admissionDate: v(fd,'admissionDate'), email: v(fd,'email') || undefined, phone: v(fd,'phone') || undefined, initialEnrollment: v(fd,'academicYearId') ? { academicYearId:v(fd,'academicYearId'), classId:v(fd,'classId'), sectionId:v(fd,'sectionId'), enrollmentDate:v(fd,'enrollmentDate'), rollNumber:v(fd,'rollNumber') || undefined } : undefined }); } catch { fail(slug); } redirect(`/s/${slug}/students?message=created` as never); }
export async function archiveStudentAction(fd: FormData) { const slug = v(fd, 'schoolSlug'); try { const c = await contextForSchoolSlug(slug); await archiveStudent(c, v(fd,'studentId')); } catch { fail(slug); } redirect(`/s/${slug}/students?message=archived` as never); }
export async function createGuardianAction(fd: FormData) { const slug = v(fd, 'schoolSlug'); try { const c = await contextForSchoolSlug(slug); await createGuardian(c, { firstName:v(fd,'firstName'), lastName:v(fd,'lastName'), phone:v(fd,'phone'), email:v(fd,'email') || undefined }); } catch { fail(slug); } redirect(`/s/${slug}/students?message=guardian-created` as never); }
export async function linkGuardianAction(fd: FormData) { const slug = v(fd, 'schoolSlug'); try { const c = await contextForSchoolSlug(slug); await linkGuardian(c, { studentId:v(fd,'studentId'), guardianId:v(fd,'guardianId'), relationship:v(fd,'relationship'), isPrimary:fd.get('isPrimary') === 'on', receivesNotifications:true, canPickup:fd.get('canPickup') === 'on' }); } catch { fail(slug); } redirect(`/s/${slug}/students?message=linked` as never); }
export async function createEnrollmentAction(fd: FormData) { const slug = v(fd, 'schoolSlug'); try { const c = await contextForSchoolSlug(slug); await createEnrollment(c, { studentId:v(fd,'studentId'), academicYearId:v(fd,'academicYearId'), classId:v(fd,'classId'), sectionId:v(fd,'sectionId'), enrollmentDate:v(fd,'enrollmentDate'), rollNumber:v(fd,'rollNumber') || undefined }); } catch { fail(slug); } redirect(`/s/${slug}/students?message=enrolled` as never); }
export async function updateStudentAction(fd: FormData) { const slug = v(fd, 'schoolSlug'); try { const c = await contextForSchoolSlug(slug); await updateStudent(c, v(fd,'studentId'), { firstName:v(fd,'firstName'), middleName:v(fd,'middleName') || undefined, lastName:v(fd,'lastName'), preferredName:v(fd,'preferredName') || undefined, gender:v(fd,'gender') || undefined, dateOfBirth:v(fd,'dateOfBirth'), admissionDate:v(fd,'admissionDate'), email:v(fd,'email') || undefined, phone:v(fd,'phone') || undefined, bloodGroup:v(fd,'bloodGroup') || undefined }); } catch { fail(slug); } redirect(`/s/${slug}/students/${v(fd,'studentId')}?message=updated` as never); }
export async function setEnrollmentStatusAction(fd: FormData) { const slug = v(fd, 'schoolSlug'); try { const c = await contextForSchoolSlug(slug); await setEnrollmentStatus(c, v(fd,'enrollmentId'), v(fd,'status') as 'ACTIVE' | 'COMPLETED' | 'WITHDRAWN' | 'CANCELLED'); } catch { fail(slug); } redirect(`/s/${slug}/students/${v(fd,'studentId')}?message=enrollment-updated` as never); }
export async function createStudentAndGuardianAction(fd: FormData) { const slug = v(fd, 'schoolSlug'); try { const c = await contextForSchoolSlug(slug); const student = await createStudentWithInitialEnrollment(c, { admissionNumber:v(fd,'admissionNumber'), firstName:v(fd,'firstName'), lastName:v(fd,'lastName'), dateOfBirth:v(fd,'dateOfBirth'), admissionDate:v(fd,'admissionDate'), initialEnrollment: { academicYearId:v(fd,'academicYearId'), classId:v(fd,'classId'), sectionId:v(fd,'sectionId'), enrollmentDate:v(fd,'enrollmentDate') } }); await createGuardian(c, { firstName:v(fd,'guardianFirstName'), lastName:v(fd,'guardianLastName'), phone:v(fd,'guardianPhone'), email:v(fd,'guardianEmail') || undefined }); void student; } catch { fail(slug); } redirect(`/s/${slug}/students?message=created` as never); }
