import { describe, expect, it, vi } from 'vitest';
vi.mock('server-only', () => ({}));
import { createEnrollment, createStudent, getStudent, getStudentPhotoUrl, linkGuardian, listStudents } from './service';
const context = { schoolId: 'school-a', schoolSlug: 'a', userId: 'user-a', membershipId: 'membership-a', role: 'SCHOOL_OWNER' as const, permissions: ['students:read', 'students:manage'] as const };
const ids = { student: '00000000-0000-4000-8000-000000000001', year: '00000000-0000-4000-8000-000000000002', cls: '00000000-0000-4000-8000-000000000003', section: '00000000-0000-4000-8000-000000000004', guardian: '00000000-0000-4000-8000-000000000005' };
describe('student tenant scope', () => {
  it('does not resolve another school student', async () => { const db = { student: { findFirst: async () => null } } as never; await expect(getStudent(context, ids.student, db)).rejects.toMatchObject({ code: 'NOT_FOUND' }); });
  it('requires all enrollment references to belong to this school', async () => { const db = { student: { findFirst: async () => ({ id: ids.student }) }, academicYear: { findFirst: async () => null }, academicClass: { findFirst: async () => ({ id: ids.cls }) }, section: { findFirst: async () => ({ id: ids.section }) }, studentEnrollment: { create: vi.fn() } } as never; await expect(createEnrollment(context, { studentId: ids.student, academicYearId: ids.year, classId: ids.cls, sectionId: ids.section, enrollmentDate: '2026-01-01' }, db)).rejects.toMatchObject({ code: 'NOT_FOUND' }); });
  it('requires student and guardian to share tenant before linking', async () => { const db = { student: { findFirst: async () => null }, guardian: { findFirst: async () => ({ id: ids.guardian }) }, studentGuardian: { create: vi.fn() } } as never; await expect(linkGuardian(context, { studentId: ids.student, guardianId: ids.guardian, relationship: 'Parent' }, db)).rejects.toMatchObject({ code: 'NOT_FOUND' }); });
  it('keeps list query tenant-scoped and paginated', async () => { let args: { where: { schoolId: string }; skip: number; take: number } | undefined; const db = { student: { findMany: async (x: { where: { schoolId: string }; skip: number; take: number }) => { args = x; return []; } } } as never; await listStudents(context, { page: 2, pageSize: 10, query: 'Ali' }, db); expect(args?.where.schoolId).toBe('school-a'); expect(args?.skip).toBe(10); expect(args?.take).toBe(10); });
  it('maps duplicate admission numbers to a conflict', async () => { const db = { student: { create: vi.fn().mockRejectedValue({ code: 'P2002' }) } } as never; await expect(createStudent(context, { admissionNumber: 'A-1', firstName: 'A', lastName: 'B', dateOfBirth: '2010-01-01', admissionDate: '2026-01-01' }, db)).rejects.toMatchObject({ code: 'CONFLICT' }); });
  it('does not issue a photo lookup for another tenant', async () => { const db = { student: { findFirst: async () => null } } as never; await expect(getStudentPhotoUrl(context, ids.student, undefined, db)).resolves.toBeNull(); });
  it('keeps enrollment creation tenant-scoped for every reference', async () => { const create = vi.fn(); const db = { student: { findFirst: async () => ({ id: ids.student }) }, academicYear: { findFirst: async () => ({ id: ids.year }) }, academicClass: { findFirst: async () => ({ id: ids.cls }) }, section: { findFirst: async () => ({ id: ids.section }) }, studentEnrollment: { create } } as never; await createEnrollment(context, { studentId: ids.student, academicYearId: ids.year, classId: ids.cls, sectionId: ids.section, enrollmentDate: '2026-01-01' }, db); expect(create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ schoolId: 'school-a' }) })); });
});
