import 'server-only';
import { randomUUID } from 'node:crypto';
import { prisma } from '@schooz/database';
import { PERMISSIONS, requireSchoolPermission, type SchoolContext } from '../authorization';
import { ConflictError, NotFoundError } from '../errors';
import { createAuthorizedDownloadUrl, uploadPrivateObjectAtKey, validateUploadMetadata, type UploadMetadata } from '../storage';
import { enrollmentSchema, guardianLinkSchema, guardianSchema, studentSchema } from './schemas';
import { assertEnrollmentStatusTransition, type EnrollmentStatus } from './state';

type StudentDb = Pick<typeof prisma, 'student' | 'guardian' | 'studentGuardian' | 'studentEnrollment' | 'academicYear' | 'academicClass' | 'section' | '$transaction'>;
const read = (c: SchoolContext) => requireSchoolPermission(c, PERMISSIONS.STUDENTS_READ);
const manage = (c: SchoolContext) => requireSchoolPermission(c, PERMISSIONS.STUDENTS_MANAGE);
const missing = (message: string): never => { throw new NotFoundError(message); };
function dbError(error: unknown): never { if (error && typeof error === 'object' && 'code' in error && (error as { code: string }).code === 'P2002') throw new ConflictError('A matching student or relationship already exists.'); throw error; }

export async function listStudents(context: SchoolContext, filters: { query?: string; status?: 'ACTIVE' | 'INACTIVE' | 'ARCHIVED'; page?: number; pageSize?: number } = {}, db: StudentDb = prisma) {
  read(context); const pageSize = Math.min(Math.max(filters.pageSize ?? 25, 1), 100); const page = Math.max(filters.page ?? 1, 1); const query = filters.query?.trim();
  return db.student.findMany({ where: { schoolId: context.schoolId, ...(filters.status ? { status: filters.status } : {}), ...(query ? { OR: [{ admissionNumber: { contains: query, mode: 'insensitive' } }, { firstName: { contains: query, mode: 'insensitive' } }, { lastName: { contains: query, mode: 'insensitive' } }] } : {}) }, select: { id: true, admissionNumber: true, firstName: true, middleName: true, lastName: true, preferredName: true, status: true, admissionDate: true }, orderBy: [{ createdAt: 'desc' }, { id: 'desc' }], skip: (page - 1) * pageSize, take: pageSize });
}
export async function getStudent(context: SchoolContext, studentId: string, db: StudentDb = prisma) { read(context); const student = await db.student.findFirst({ where: { id: studentId, schoolId: context.schoolId }, include: { guardians: { include: { guardian: true } }, enrollments: { include: { academicYear: true, academicClass: true, section: true }, orderBy: { enrollmentDate: 'desc' } } } }); return student ?? missing('Student not found.'); }
export async function createStudent(context: SchoolContext, input: unknown, db: StudentDb = prisma) { manage(context); const data = studentSchema.parse(input); try { return await db.student.create({ data: { ...data, schoolId: context.schoolId } }); } catch (e) { dbError(e); } }
export async function archiveStudent(context: SchoolContext, studentId: string, db: StudentDb = prisma) { manage(context); const result = await db.student.updateMany({ where: { id: studentId, schoolId: context.schoolId }, data: { status: 'ARCHIVED', archivedAt: new Date() } }); if (!result.count) missing('Student not found.'); return result; }

export async function listGuardians(context: SchoolContext, query?: string, db: StudentDb = prisma) { read(context); return db.guardian.findMany({ where: { schoolId: context.schoolId, ...(query ? { OR: [{ firstName: { contains: query, mode: 'insensitive' } }, { lastName: { contains: query, mode: 'insensitive' } }, { phone: { contains: query } }] } : {}) }, orderBy: [{ lastName: 'asc' }, { firstName: 'asc' }], take: 100 }); }
export async function createGuardian(context: SchoolContext, input: unknown, db: StudentDb = prisma) { manage(context); const data = guardianSchema.parse(input); try { return await db.guardian.create({ data: { ...data, schoolId: context.schoolId } }); } catch (e) { dbError(e); } }
export async function linkGuardian(context: SchoolContext, input: unknown, db: StudentDb = prisma) { manage(context); const data = guardianLinkSchema.parse(input); const [student, guardian] = await Promise.all([db.student.findFirst({ where: { id: data.studentId, schoolId: context.schoolId } }), db.guardian.findFirst({ where: { id: data.guardianId, schoolId: context.schoolId } })]); if (!student || !guardian) missing('Student or guardian not found.'); try { return await db.studentGuardian.create({ data: { ...data, schoolId: context.schoolId } }); } catch (e) { dbError(e); } }

export async function createEnrollment(context: SchoolContext, input: unknown, db: StudentDb = prisma) { manage(context); const data = enrollmentSchema.parse(input); const [student, year, cls, section] = await Promise.all([db.student.findFirst({ where: { id: data.studentId, schoolId: context.schoolId } }), db.academicYear.findFirst({ where: { id: data.academicYearId, schoolId: context.schoolId } }), db.academicClass.findFirst({ where: { id: data.classId, schoolId: context.schoolId } }), db.section.findFirst({ where: { id: data.sectionId, schoolId: context.schoolId, academicYearId: data.academicYearId, classId: data.classId } })]); if (!student || !year || !cls || !section) missing('Enrollment records must belong to this school and matching academic structure.'); try { return await db.studentEnrollment.create({ data: { ...data, schoolId: context.schoolId } }); } catch (e) { dbError(e); } }
export async function setEnrollmentStatus(context: SchoolContext, enrollmentId: string, status: EnrollmentStatus, db: StudentDb = prisma) { manage(context); const current = await db.studentEnrollment.findFirst({ where: { id: enrollmentId, schoolId: context.schoolId } }); if (!current) return missing('Enrollment not found.'); assertEnrollmentStatusTransition(current.status, status); return db.studentEnrollment.update({ where: { id: enrollmentId }, data: { status } }); }
export async function uploadStudentPhoto(context: SchoolContext, studentId: string, file: Blob | ArrayBuffer | Uint8Array, metadata: UploadMetadata, db: StudentDb = prisma) { manage(context); const student = await db.student.findFirst({ where: { id: studentId, schoolId: context.schoolId } }); if (!student) missing('Student not found.'); const valid = validateUploadMetadata(metadata); if (!['image/jpeg', 'image/png', 'image/webp'].includes(valid.contentType)) throw new ConflictError('Student photos must be JPEG, PNG or WebP.'); const key = `schools/${context.schoolId}/students/${studentId}/${randomUUID()}`; const uploaded = await uploadPrivateObjectAtKey({ storageKey: key, allowedPrefix: `schools/${context.schoolId}/students/${studentId}`, file, metadata: valid }); await db.student.update({ where: { id: studentId }, data: { photoStorageKey: uploaded.storageKey } }); return uploaded; }
export async function getStudentPhotoUrl(context: SchoolContext, studentId: string, storage?: Parameters<typeof createAuthorizedDownloadUrl>[0]['storage'], db: StudentDb = prisma) { read(context); const student = await db.student.findFirst({ where: { id: studentId, schoolId: context.schoolId }, select: { photoStorageKey: true } }); if (!student?.photoStorageKey) return null; return createAuthorizedDownloadUrl({ context, schoolId: context.schoolId, storageKey: student.photoStorageKey, storage }); }
