import 'server-only';
import { prisma } from '@schooz/database';
import { PERMISSIONS, requireSchoolPermission, type SchoolContext } from '../authorization';
import { ConflictError, NotFoundError } from '../errors';
import { examSchema, examUpdateSchema, gradingSchemeSchema, scheduleSchema } from './schemas';
import { assertExamStatusTransition, type ExamStatus } from './state';
import { validateGradingRanges } from './grading';
type ExamDb = Pick<typeof prisma, 'exam' | 'examSchedule' | 'academicYear' | 'academicClass' | 'subject' | 'classSubject' | 'gradingScheme' | 'gradingScaleItem' | '$transaction'>;
const read = (c: SchoolContext) => requireSchoolPermission(c, PERMISSIONS.EXAMS_READ ?? PERMISSIONS.EXAMS_RESULTS_READ);
const manage = (c: SchoolContext) => requireSchoolPermission(c, PERMISSIONS.EXAMS_MANAGE ?? PERMISSIONS.EXAMS_RESULTS_MANAGE);
const missing = (m: string): never => { throw new NotFoundError(m); };
const conflict = (e: unknown): never => { if (e && typeof e === 'object' && 'code' in e && (e as { code: string }).code === 'P2002') throw new ConflictError('A matching exam, schedule, or grading record already exists.'); throw e; };
export async function listExams(context: SchoolContext, filters: { academicYearId?: string; status?: ExamStatus; page?: number; pageSize?: number } = {}, db: ExamDb = prisma) { read(context); const pageSize = Math.min(Math.max(filters.pageSize ?? 25, 1), 100); const page = Math.max(filters.page ?? 1, 1); const items = await db.exam.findMany({ where: { schoolId: context.schoolId, ...(filters.academicYearId ? { academicYearId: filters.academicYearId } : {}), ...(filters.status ? { status: filters.status } : {}) }, select: { id: true, academicYearId: true, name: true, examType: true, startDate: true, endDate: true, status: true }, orderBy: [{ startDate: 'desc' }, { id: 'desc' }], skip: (page - 1) * pageSize, take: pageSize }); return { items, page, pageSize, hasMore: items.length === pageSize }; }
export async function getExam(context: SchoolContext, examId: string, db: ExamDb = prisma) { read(context); const exam = await db.exam.findFirst({ where: { id: examId, schoolId: context.schoolId }, include: { schedules: { take: 500, include: { academicClass: { select: { name: true } }, subject: { select: { name: true, code: true } } }, orderBy: [{ examDate: 'asc' }, { startTime: 'asc' }] } } }); return exam ?? missing('Exam not found.'); }
export async function createExam(context: SchoolContext, input: unknown, db: ExamDb = prisma) { manage(context); const data = examSchema.parse(input); const year = await db.academicYear.findFirst({ where: { id: data.academicYearId, schoolId: context.schoolId } }); if (!year) missing('Academic year not found.'); try { return await db.exam.create({ data: { ...data, schoolId: context.schoolId } }); } catch (e) { conflict(e); } }
export async function updateExam(context: SchoolContext, examId: string, input: unknown, db: ExamDb = prisma) { manage(context); const data = examUpdateSchema.parse(input); const result = await db.exam.updateMany({ where: { id: examId, schoolId: context.schoolId }, data }); if (!result.count) missing('Exam not found.'); return db.exam.findFirst({ where: { id: examId, schoolId: context.schoolId } }); }
export async function setExamStatus(context: SchoolContext, examId: string, status: ExamStatus, db: ExamDb = prisma) { manage(context); const exam = await db.exam.findFirst({ where: { id: examId, schoolId: context.schoolId } }); if (!exam) return missing('Exam not found.'); assertExamStatusTransition(exam.status, status); return db.exam.update({ where: { id: examId }, data: { status } }); }
export async function createSchedule(context: SchoolContext, input: unknown, db: ExamDb = prisma) { manage(context); const data = scheduleSchema.parse(input); const exam = await db.exam.findFirst({ where: { id: data.examId, schoolId: context.schoolId } }); if (!exam) return missing('Exam not found.'); if (data.examDate < exam.startDate || data.examDate > exam.endDate) throw new ConflictError('Exam date must fall inside the exam window.'); const [cls, subject, mapping] = await Promise.all([db.academicClass.findFirst({ where: { id: data.classId, schoolId: context.schoolId } }), db.subject.findFirst({ where: { id: data.subjectId, schoolId: context.schoolId } }), db.classSubject.findFirst({ where: { schoolId: context.schoolId, academicYearId: exam.academicYearId, classId: data.classId, subjectId: data.subjectId } })]); if (!cls || !subject || !mapping) missing('Schedule class, subject, and class-subject mapping must belong to this school and academic year.'); try { return await db.examSchedule.create({ data: { ...data, schoolId: context.schoolId } }); } catch (e) { conflict(e); } }
export async function listGradingSchemes(context: SchoolContext, db: ExamDb = prisma) { read(context); return db.gradingScheme.findMany({ where: { schoolId: context.schoolId }, include: { items: { orderBy: { sortOrder: 'asc' } } }, orderBy: [{ isDefault: 'desc' }, { name: 'asc' }], take: 100 }); }
export async function createGradingScheme(context: SchoolContext, input: unknown, db: ExamDb = prisma) { manage(context); const data = gradingSchemeSchema.parse(input); const items = validateGradingRanges(data.items); try { return await db.$transaction(async tx => { if (data.isDefault) await tx.gradingScheme.updateMany({ where: { schoolId: context.schoolId, isDefault: true }, data: { isDefault: false } }); return tx.gradingScheme.create({ data: { schoolId: context.schoolId, name: data.name, isDefault: data.isDefault, items: { create: items } } }); }); } catch (e) { conflict(e); } }
export async function setDefaultGradingScheme(context: SchoolContext, schemeId: string, db: ExamDb = prisma) { manage(context); const scheme = await db.gradingScheme.findFirst({ where: { id: schemeId, schoolId: context.schoolId } }); if (!scheme) missing('Grading scheme not found.'); return db.$transaction(async tx => { await tx.gradingScheme.updateMany({ where: { schoolId: context.schoolId, isDefault: true }, data: { isDefault: false } }); return tx.gradingScheme.update({ where: { id: schemeId }, data: { isDefault: true } }); }); }
