import 'server-only';
import { prisma } from '@schooz/database';
import { requireSchoolPermission, type SchoolContext, PERMISSIONS } from '../authorization';
import { ConflictError, NotFoundError } from '../errors';
import { academicClassSchema, academicYearSchema, classSubjectSchema, sectionSchema, subjectSchema } from './schemas';
import { assertAcademicStatusTransition, type AcademicStatus } from './state';

type AcademicDb = Pick<typeof prisma, 'academicYear' | 'academicClass' | 'section' | 'subject' | 'classSubject' | '$transaction'>;
const read = (c: SchoolContext) => requireSchoolPermission(c, PERMISSIONS.ACADEMICS_READ);
const manage = (c: SchoolContext) => requireSchoolPermission(c, PERMISSIONS.ACADEMICS_MANAGE);
const notFound = (message: string) => { throw new NotFoundError(message); };
const conflict = (e: unknown) => { if (e && typeof e === 'object' && 'code' in e && (e as { code: string }).code === 'P2002') throw new ConflictError('A record with these values already exists.'); throw e; };

export async function listAcademicYears(context: SchoolContext, db: AcademicDb = prisma) { read(context); return db.academicYear.findMany({ where: { schoolId: context.schoolId }, orderBy: { startDate: 'desc' }, take: 100 }); }
export async function createAcademicYear(context: SchoolContext, input: unknown, db: AcademicDb = prisma) { manage(context); const data = academicYearSchema.parse(input); try { return await db.academicYear.create({ data: { ...data, schoolId: context.schoolId } }); } catch (e) { conflict(e); } }
export async function setCurrentAcademicYear(context: SchoolContext, id: string, db: AcademicDb = prisma) { manage(context); const target = await db.academicYear.findFirst({ where: { id, schoolId: context.schoolId } }); if (!target) return notFound('Academic year not found.'); try { return await db.$transaction(async tx => { await tx.academicYear.updateMany({ where: { schoolId: context.schoolId, isCurrent: true }, data: { isCurrent: false } }); return tx.academicYear.update({ where: { id: target.id }, data: { isCurrent: true } }); }); } catch (e) { conflict(e); } }
export async function setAcademicYearStatus(context: SchoolContext, id: string, status: AcademicStatus, db: AcademicDb = prisma) { manage(context); const current = await db.academicYear.findFirst({ where: { id, schoolId: context.schoolId } }); if (!current) return notFound('Academic year not found.'); assertAcademicStatusTransition(current.status, status); return db.academicYear.update({ where: { id }, data: { status } }); }

export async function listAcademicClasses(context: SchoolContext, db: AcademicDb = prisma) { read(context); return db.academicClass.findMany({ where: { schoolId: context.schoolId }, orderBy: [{ sortOrder: 'asc' }, { name: 'asc' }], take: 200 }); }
export async function createAcademicClass(context: SchoolContext, input: unknown, db: AcademicDb = prisma) { manage(context); const data = academicClassSchema.parse(input); try { return await db.academicClass.create({ data: { ...data, schoolId: context.schoolId } }); } catch (e) { conflict(e); } }
export async function setAcademicClassStatus(context: SchoolContext, id: string, status: AcademicStatus, db: AcademicDb = prisma) { manage(context); const current = await db.academicClass.findFirst({ where: { id, schoolId: context.schoolId } }); if (!current) return notFound('Class not found.'); assertAcademicStatusTransition(current.status, status); return db.academicClass.update({ where: { id }, data: { status } }); }

export async function listSubjects(context: SchoolContext, db: AcademicDb = prisma) { read(context); return db.subject.findMany({ where: { schoolId: context.schoolId }, orderBy: { name: 'asc' }, take: 300 }); }
export async function createSubject(context: SchoolContext, input: unknown, db: AcademicDb = prisma) { manage(context); const data = subjectSchema.parse(input); try { return await db.subject.create({ data: { ...data, schoolId: context.schoolId } }); } catch (e) { conflict(e); } }
export async function setSubjectStatus(context: SchoolContext, id: string, status: AcademicStatus, db: AcademicDb = prisma) { manage(context); const current = await db.subject.findFirst({ where: { id, schoolId: context.schoolId } }); if (!current) return notFound('Subject not found.'); assertAcademicStatusTransition(current.status, status); return db.subject.update({ where: { id }, data: { status } }); }

export async function listSections(context: SchoolContext, filters: { academicYearId?: string; classId?: string } = {}, db: AcademicDb = prisma) { read(context); return db.section.findMany({ where: { schoolId: context.schoolId, ...(filters.academicYearId ? { academicYearId: filters.academicYearId } : {}), ...(filters.classId ? { classId: filters.classId } : {}) }, include: { academicClass: { select: { name: true } }, academicYear: { select: { name: true } } }, orderBy: { name: 'asc' }, take: 300 }); }
export async function createSection(context: SchoolContext, input: unknown, db: AcademicDb = prisma) { manage(context); const data = sectionSchema.parse(input); const [year, cls] = await Promise.all([db.academicYear.findFirst({ where: { id: data.academicYearId, schoolId: context.schoolId } }), db.academicClass.findFirst({ where: { id: data.classId, schoolId: context.schoolId } })]); if (!year || !cls) return notFound('Academic year or class is not in this school.'); try { return await db.section.create({ data: { ...data, schoolId: context.schoolId } }); } catch (e) { conflict(e); } }
export async function setSectionStatus(context: SchoolContext, id: string, status: AcademicStatus, db: AcademicDb = prisma) { manage(context); const current = await db.section.findFirst({ where: { id, schoolId: context.schoolId } }); if (!current) return notFound('Section not found.'); assertAcademicStatusTransition(current.status, status); return db.section.update({ where: { id }, data: { status } }); }

export async function listClassSubjects(context: SchoolContext, academicYearId?: string, db: AcademicDb = prisma) { read(context); return db.classSubject.findMany({ where: { schoolId: context.schoolId, ...(academicYearId ? { academicYearId } : {}) }, include: { academicClass: { select: { name: true } }, subject: { select: { name: true, code: true } }, academicYear: { select: { name: true } } }, orderBy: { createdAt: 'desc' }, take: 500 }); }
export async function createClassSubject(context: SchoolContext, input: unknown, db: AcademicDb = prisma) { manage(context); const data = classSubjectSchema.parse(input); const [year, cls, subject] = await Promise.all([db.academicYear.findFirst({ where: { id: data.academicYearId, schoolId: context.schoolId } }), db.academicClass.findFirst({ where: { id: data.classId, schoolId: context.schoolId } }), db.subject.findFirst({ where: { id: data.subjectId, schoolId: context.schoolId } })]); if (!year || !cls || !subject) return notFound('Class, subject or academic year is not in this school.'); try { return await db.classSubject.create({ data: { ...data, schoolId: context.schoolId } }); } catch (e) { conflict(e); } }
