'use server';
import { redirect } from 'next/navigation';
import { contextForSchoolSlug } from '../settings/service';
import { createAssignment, createTeacher, deactivateTeacher, updateTeacher } from './service';
const v = (fd: FormData, key: string) => { const x = fd.get(key); return typeof x === 'string' ? x : ''; };
const fail = (slug: string): never => redirect('/s/' + slug + '/teachers?error=action-failed' as never);
export async function createTeacherAction(fd: FormData) { const slug = v(fd, 'schoolSlug'); try { const c = await contextForSchoolSlug(slug); await createTeacher(c, { employeeNumber:v(fd,'employeeNumber'), firstName:v(fd,'firstName'), middleName:v(fd,'middleName') || undefined, lastName:v(fd,'lastName'), email:v(fd,'email') || undefined, phone:v(fd,'phone') || undefined, dateOfBirth:v(fd,'dateOfBirth') || undefined, joinDate:v(fd,'joinDate'), qualification:v(fd,'qualification') || undefined, designation:v(fd,'designation') || undefined }); } catch { fail(slug); } redirect('/teachers' as never); }
export async function updateTeacherAction(fd: FormData) { const slug = v(fd, 'schoolSlug'); try { const c = await contextForSchoolSlug(slug); await updateTeacher(c, v(fd,'teacherId'), { firstName:v(fd,'firstName'), middleName:v(fd,'middleName') || undefined, lastName:v(fd,'lastName'), email:v(fd,'email') || undefined, phone:v(fd,'phone') || undefined, dateOfBirth:v(fd,'dateOfBirth') || undefined, joinDate:v(fd,'joinDate'), qualification:v(fd,'qualification') || undefined, designation:v(fd,'designation') || undefined }); } catch { fail(slug); } redirect('/teachers' as never); }
export async function deactivateTeacherAction(fd: FormData) { const slug = v(fd, 'schoolSlug'); try { const c = await contextForSchoolSlug(slug); await deactivateTeacher(c, v(fd,'teacherId')); } catch { fail(slug); } redirect('/teachers' as never); }
export async function createAssignmentAction(fd: FormData) { const slug = v(fd, 'schoolSlug'); try { const c = await contextForSchoolSlug(slug); await createAssignment(c, { teacherId:v(fd,'teacherId'), academicYearId:v(fd,'academicYearId'), classId:v(fd,'classId'), sectionId:v(fd,'sectionId') || undefined, subjectId:v(fd,'subjectId') }); } catch { fail(slug); } redirect('/teachers' as never); }
