import 'server-only';
import { randomUUID } from 'node:crypto';
import { prisma } from '@schooz/database';
import { PERMISSIONS, requireSchoolPermission, type SchoolContext } from '../authorization';
import { ConflictError, NotFoundError } from '../errors';
import { createAuthorizedDownloadUrl, uploadPrivateObjectAtKey, validateUploadMetadata, type UploadMetadata } from '../storage';
import { assignmentSchema, teacherSchema, teacherUpdateSchema, type TeacherStatus } from './schemas';
type TeacherDb = Pick<typeof prisma, 'teacher' | 'teacherAssignment' | 'academicYear' | 'academicClass' | 'section' | 'subject' | 'classSubject'>;
const read = (c: SchoolContext) => requireSchoolPermission(c, PERMISSIONS.TEACHERS_READ);
const manage = (c: SchoolContext) => requireSchoolPermission(c, PERMISSIONS.TEACHERS_MANAGE);
const missing = (m: string): never => { throw new NotFoundError(m); };
const dbError = (e: unknown): never => { if (e && typeof e === 'object' && 'code' in e && (e as { code: string }).code === 'P2002') throw new ConflictError('Teacher or assignment already exists.'); throw e; };
export async function listTeachers(context: SchoolContext, filters: { query?: string; status?: TeacherStatus; page?: number; pageSize?: number } = {}, db: TeacherDb = prisma) { read(context); const pageSize = Math.min(Math.max(filters.pageSize ?? 25, 1), 100); const page = Math.max(filters.page ?? 1, 1); const q = filters.query?.trim(); const items = await db.teacher.findMany({ where: { schoolId: context.schoolId, ...(filters.status ? { status: filters.status } : {}), ...(q ? { OR: [{ employeeNumber: { contains: q, mode: 'insensitive' } }, { firstName: { contains: q, mode: 'insensitive' } }, { lastName: { contains: q, mode: 'insensitive' } }] } : {}) }, select: { id: true, employeeNumber: true, firstName: true, middleName: true, lastName: true, email: true, phone: true, designation: true, status: true, joinDate: true }, orderBy: [{ createdAt: 'desc' }, { id: 'desc' }], skip: (page - 1) * pageSize, take: pageSize }); return { items, page, pageSize, hasMore: items.length === pageSize }; }
export async function getTeacher(context: SchoolContext, teacherId: string, db: TeacherDb = prisma) { read(context); const teacher = await db.teacher.findFirst({ where: { id: teacherId, schoolId: context.schoolId }, include: { assignments: { take: 200, include: { academicYear: { select: { name: true } }, academicClass: { select: { name: true } }, section: { select: { name: true } }, subject: { select: { name: true, code: true } } }, orderBy: { createdAt: 'desc' } } } }); return teacher ?? missing('Teacher not found.'); }
export async function createTeacher(context: SchoolContext, input: unknown, db: TeacherDb = prisma) { manage(context); const data = teacherSchema.parse(input); try { return await db.teacher.create({ data: { ...data, schoolId: context.schoolId } }); } catch (e) { dbError(e); } }
export async function updateTeacher(context: SchoolContext, teacherId: string, input: unknown, db: TeacherDb = prisma) { manage(context); const data = teacherUpdateSchema.parse(input); const result = await db.teacher.updateMany({ where: { id: teacherId, schoolId: context.schoolId }, data }); if (!result.count) missing('Teacher not found.'); return db.teacher.findFirst({ where: { id: teacherId, schoolId: context.schoolId } }); }
export async function deactivateTeacher(context: SchoolContext, teacherId: string, db: TeacherDb = prisma) { manage(context); const result = await db.teacher.updateMany({ where: { id: teacherId, schoolId: context.schoolId }, data: { status: 'INACTIVE' } }); if (!result.count) missing('Teacher not found.'); return result; }
export async function createAssignment(context: SchoolContext, input: unknown, db: TeacherDb = prisma) { manage(context); const data = assignmentSchema.parse(input); const [teacher, year, cls, section, subject, mapping] = await Promise.all([db.teacher.findFirst({ where: { id: data.teacherId, schoolId: context.schoolId } }), db.academicYear.findFirst({ where: { id: data.academicYearId, schoolId: context.schoolId } }), db.academicClass.findFirst({ where: { id: data.classId, schoolId: context.schoolId } }), data.sectionId ? db.section.findFirst({ where: { id: data.sectionId, schoolId: context.schoolId, academicYearId: data.academicYearId, classId: data.classId } }) : Promise.resolve(true), db.subject.findFirst({ where: { id: data.subjectId, schoolId: context.schoolId } }), db.classSubject.findFirst({ where: { schoolId: context.schoolId, academicYearId: data.academicYearId, classId: data.classId, subjectId: data.subjectId } })]); if (!teacher || !year || !cls || !section || !subject || !mapping) missing('Assignment references must belong to this school and class-subject mapping.'); try { return await db.teacherAssignment.create({ data: { ...data, schoolId: context.schoolId } }); } catch (e) { dbError(e); } }
export async function listAssignments(context: SchoolContext, filters: { academicYearId?: string; teacherId?: string; classId?: string; sectionId?: string } = {}, db: TeacherDb = prisma) { read(context); return db.teacherAssignment.findMany({ where: { schoolId: context.schoolId, ...filters }, include: { teacher: { select: { firstName: true, lastName: true, employeeNumber: true } }, academicClass: { select: { name: true } }, section: { select: { name: true } }, subject: { select: { name: true, code: true } }, academicYear: { select: { name: true } } }, orderBy: { createdAt: 'desc' }, take: 500 }); }
export async function uploadTeacherPhoto(context: SchoolContext, teacherId: string, file: Blob | ArrayBuffer | Uint8Array, metadata: UploadMetadata, db: TeacherDb = prisma) { manage(context); const teacher = await db.teacher.findFirst({ where: { id: teacherId, schoolId: context.schoolId } }); if (!teacher) missing('Teacher not found.'); const valid = validateUploadMetadata(metadata); if (!['image/jpeg', 'image/png', 'image/webp'].includes(valid.contentType)) throw new ConflictError('Teacher photos must be JPEG, PNG or WebP.'); const key = `schools/${context.schoolId}/teachers/${teacherId}/${randomUUID()}`; const uploaded = await uploadPrivateObjectAtKey({ storageKey: key, allowedPrefix: `schools/${context.schoolId}/teachers/${teacherId}`, file, metadata: valid }); await db.teacher.update({ where: { id: teacherId }, data: { photoStorageKey: uploaded.storageKey } }); return uploaded; }
export async function getTeacherPhotoUrl(context: SchoolContext, teacherId: string, storage?: Parameters<typeof createAuthorizedDownloadUrl>[0]['storage'], db: TeacherDb = prisma) { read(context); const teacher = await db.teacher.findFirst({ where: { id: teacherId, schoolId: context.schoolId }, select: { photoStorageKey: true } }); if (!teacher?.photoStorageKey) return null; return createAuthorizedDownloadUrl({ context, schoolId: context.schoolId, storageKey: teacher.photoStorageKey, storage }); }
