import { resolveSchoolContextCached } from '@/server/authorization';
import { PageHeader, DataTable, StatusBadge, EmptyState } from '@/components/tenant';
import { listStudents, listGuardians } from '@/server/students/service';
import { createStudentAction, createGuardianAction, archiveStudentAction } from '@/server/students/actions';
function Hidden({ slug }: { slug: string }) { return <input type='hidden' name='schoolSlug' value={slug}/>; }
export default async function StudentsPage({ params, searchParams }: { params: Promise<{ schoolSlug: string }>; searchParams: Promise<{ q?: string }> }) {
  const { schoolSlug } = await params; const query = (await searchParams).q; const context = await resolveSchoolContextCached(schoolSlug); const [students, guardians] = await Promise.all([listStudents(context, { query }), listGuardians(context, query)]); const canManage = context.permissions.includes('students:manage');
  return <div><PageHeader eyebrow='People' title='Students and guardians' description='Permanent student records with tenant-scoped enrollment history.' />
    <section className='settings-card'><form className='auth-form'><input name='q' defaultValue={query} placeholder='Search name or admission number'/><button type='submit'>Search</button></form></section>
    {canManage && <section className='settings-card'><h2>Add student</h2><form action={createStudentAction} className='auth-form'><Hidden slug={schoolSlug}/><input name='admissionNumber' placeholder='Admission number' required/><input name='firstName' placeholder='First name' required/><input name='lastName' placeholder='Last name' required/><input name='dateOfBirth' type='date' required/><input name='admissionDate' type='date' required/><input name='email' type='email' placeholder='Email'/><input name='phone' placeholder='Phone'/><button type='submit'>Create student</button></form></section>}
    <section className='settings-card'><h2>Students</h2>{students.length ? <DataTable headers={['Admission','Name','Status','Action']}>{students.map(s=><tr key={s.id}><td>{s.admissionNumber}</td><td>{s.preferredName ?? `${s.firstName} ${s.lastName}`}</td><td><StatusBadge status={s.status}/></td><td><a href={`/s/${schoolSlug}/students/${s.id}`}>View</a>{canManage && s.status !== 'ARCHIVED' && <form action={archiveStudentAction}><Hidden slug={schoolSlug}/><input type='hidden' name='studentId' value={s.id}/><button type='submit'>Archive</button></form>}</td></tr>)}</DataTable> : <EmptyState title='No students found' description='Create a student or adjust your search.'/>}</section>
    {canManage && <section className='settings-card'><h2>Add guardian</h2><form action={createGuardianAction} className='auth-form'><Hidden slug={schoolSlug}/><input name='firstName' placeholder='First name' required/><input name='lastName' placeholder='Last name' required/><input name='phone' placeholder='Phone' required/><input name='email' type='email' placeholder='Email'/><button type='submit'>Create guardian</button></form></section>}
    <section className='settings-card'><h2>Guardians</h2><DataTable headers={['Name','Phone','Email']}>{guardians.map(g=><tr key={g.id}><td>{g.firstName} {g.lastName}</td><td>{g.phone}</td><td>{g.email ?? '—'}</td></tr>)}</DataTable></section>
  </div>;
}
