import type { ReactNode } from 'react';
import { resolveSchoolContextCached } from '@/server/authorization';
import { PageHeader, DataTable, StatusBadge, EmptyState } from '@/components/tenant';
import { listAcademicClasses, listAcademicYears, listClassSubjects, listSections, listSubjects } from '@/server/academics/service';
import * as actions from '@/server/academics/actions';

function Hidden({ slug }: { slug: string }) { return <input type='hidden' name='schoolSlug' value={slug} />; }
function Form({ action, children, slug }: { action: (fd: FormData) => Promise<void>; children: ReactNode; slug: string }) { return <form action={action} className='auth-form'><Hidden slug={slug} />{children}<button type='submit'>Create</button></form>; }

export default async function AcademicsPage({ params }: { params: Promise<{ schoolSlug: string }> }) {
  const { schoolSlug } = await params; const context = await resolveSchoolContextCached(schoolSlug);
  const [years, classes, subjects, sections, mappings] = await Promise.all([listAcademicYears(context), listAcademicClasses(context), listSubjects(context), listSections(context), listClassSubjects(context)]);
  const canManage = context.permissions.includes('academics:manage');
  return <div><PageHeader eyebrow='Academic structure' title='Academics' description='Manage academic years, classes, sections, subjects and class mappings.' />
    {canManage && <section className='settings-card'><h2>Add academic year</h2><Form action={actions.createAcademicYearAction} slug={schoolSlug}><input name='name' placeholder='2026–2027' required /><input name='startDate' type='date' required /><input name='endDate' type='date' required /></Form></section>}
    <section className='settings-card'><h2>Academic years</h2>{years.length ? <DataTable headers={['Name','Dates','Status','Current','Action']}>{years.map(y => <tr key={y.id}><td>{y.name}</td><td>{y.startDate.toISOString().slice(0,10)} → {y.endDate.toISOString().slice(0,10)}</td><td><StatusBadge status={y.status} /></td><td>{y.isCurrent ? 'Yes' : 'No'}</td><td>{canManage && <>{!y.isCurrent && <form action={actions.currentAcademicYearAction}><Hidden slug={schoolSlug}/><input type='hidden' name='id' value={y.id}/><button type='submit'>Make current</button></form>}<form action={actions.toggleAcademicYearAction}><Hidden slug={schoolSlug}/><input type='hidden' name='id' value={y.id}/><input type='hidden' name='status' value={y.status === 'ACTIVE' ? 'ARCHIVED' : 'ACTIVE'}/><button type='submit'>{y.status === 'ACTIVE' ? 'Archive' : 'Reactivate'}</button></form></>}</td></tr>)}</DataTable> : <EmptyState title='No academic years' description='Create the first academic year.' />}</section>
    {canManage && <section className='settings-card'><h2>Add class</h2><Form action={actions.createAcademicClassAction} slug={schoolSlug}><input name='name' placeholder='Grade 1' required/><input name='code' placeholder='G1'/><input name='sortOrder' type='number' placeholder='1'/></Form></section>}
    <section className='settings-card'><h2>Classes</h2><DataTable headers={['Name','Code','Status','Action']}>{classes.map(c => <tr key={c.id}><td>{c.name}</td><td>{c.code ?? '—'}</td><td><StatusBadge status={c.status}/></td><td>{canManage && <form action={actions.toggleAcademicClassAction}><Hidden slug={schoolSlug}/><input type='hidden' name='id' value={c.id}/><input type='hidden' name='status' value={c.status === 'ACTIVE' ? 'ARCHIVED' : 'ACTIVE'}/><button type='submit'>{c.status === 'ACTIVE' ? 'Archive' : 'Reactivate'}</button></form>}</td></tr>)}</DataTable></section>
    {canManage && <section className='settings-card'><h2>Add subject</h2><Form action={actions.createSubjectAction} slug={schoolSlug}><input name='name' placeholder='Mathematics' required/><input name='code' placeholder='MATH' required/></Form></section>}
    <section className='settings-card'><h2>Subjects</h2><DataTable headers={['Name','Code','Status','Action']}>{subjects.map(s => <tr key={s.id}><td>{s.name}</td><td>{s.code}</td><td><StatusBadge status={s.status}/></td><td>{canManage && <form action={actions.toggleSubjectAction}><Hidden slug={schoolSlug}/><input type='hidden' name='id' value={s.id}/><input type='hidden' name='status' value={s.status === 'ACTIVE' ? 'ARCHIVED' : 'ACTIVE'}/><button type='submit'>{s.status === 'ACTIVE' ? 'Archive' : 'Reactivate'}</button></form>}</td></tr>)}</DataTable></section>
    {canManage && years.length > 0 && classes.length > 0 && <section className='settings-card'><h2>Add section</h2><Form action={actions.createSectionAction} slug={schoolSlug}><select name='academicYearId' required>{years.map(y => <option key={y.id} value={y.id}>{y.name}</option>)}</select><select name='classId' required>{classes.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select><input name='name' placeholder='A' required/><input name='capacity' type='number' placeholder='Capacity'/></Form></section>}
    <section className='settings-card'><h2>Sections</h2><DataTable headers={['Year','Class','Name','Status','Action']}>{sections.map(s => <tr key={s.id}><td>{s.academicYear.name}</td><td>{s.academicClass.name}</td><td>{s.name}</td><td><StatusBadge status={s.status}/></td><td>{canManage && <form action={actions.toggleSectionAction}><Hidden slug={schoolSlug}/><input type='hidden' name='id' value={s.id}/><input type='hidden' name='status' value={s.status === 'ACTIVE' ? 'ARCHIVED' : 'ACTIVE'}/><button type='submit'>{s.status === 'ACTIVE' ? 'Archive' : 'Reactivate'}</button></form>}</td></tr>)}</DataTable></section>
    {canManage && years.length > 0 && classes.length > 0 && subjects.length > 0 && <section className='settings-card'><h2>Map class subject</h2><Form action={actions.createClassSubjectAction} slug={schoolSlug}><select name='academicYearId' required>{years.map(y => <option key={y.id} value={y.id}>{y.name}</option>)}</select><select name='classId' required>{classes.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select><select name='subjectId' required>{subjects.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select><input name='maxMarks' type='number' placeholder='Max marks'/><input name='passMarks' type='number' placeholder='Pass marks'/></Form></section>}
    <section className='settings-card'><h2>Class subjects</h2><DataTable headers={['Year','Class','Subject','Marks']}>{mappings.map(m => <tr key={m.id}><td>{m.academicYear.name}</td><td>{m.academicClass.name}</td><td>{m.subject.name} ({m.subject.code})</td><td>{m.passMarks ?? '—'} / {m.maxMarks ?? '—'}</td></tr>)}</DataTable></section>
  </div>;
}
